-- Enginu MVP data model. Run in the Supabase SQL editor.
create extension if not exists "uuid-ossp";
create type public.user_role as enum ('engineer','expert','admin','company');
create type public.assessment_status as enum ('draft','booked','completed','cancelled');
create table public.profiles (id uuid primary key references auth.users on delete cascade, role public.user_role not null default 'engineer', full_name text not null, headline text, city text, bio text, avatar_url text, public_slug text unique, is_public boolean not null default false, created_at timestamptz not null default now());
create table public.expert_profiles (user_id uuid primary key references public.profiles on delete cascade, specialties text[] not null default '{}', years_experience int, verification_status text not null default 'pending', hourly_price_egp int, rating numeric(2,1) default 0);
create table public.assessment_tracks (id uuid primary key default uuid_generate_v4(), name text not null, description text, duration_minutes int not null default 60, active boolean not null default true);
create table public.availability_slots (id uuid primary key default uuid_generate_v4(), expert_id uuid not null references public.profiles, starts_at timestamptz not null, ends_at timestamptz not null, is_booked boolean not null default false);
create table public.assessments (id uuid primary key default uuid_generate_v4(), engineer_id uuid not null references public.profiles, expert_id uuid not null references public.profiles, track_id uuid not null references public.assessment_tracks, slot_id uuid unique references public.availability_slots, status public.assessment_status not null default 'draft', meeting_url text, price_egp int, created_at timestamptz not null default now(), completed_at timestamptz);
create table public.scorecards (id uuid primary key default uuid_generate_v4(), assessment_id uuid unique not null references public.assessments on delete cascade, technical_knowledge smallint check (technical_knowledge between 1 and 5), problem_solving smallint check (problem_solving between 1 and 5), software_skills smallint check (software_skills between 1 and 5), engineering_judgment smallint check (engineering_judgment between 1 and 5), communication smallint check (communication between 1 and 5), strengths text, improvement_areas text, expert_feedback text, total_score smallint check (total_score between 0 and 100), level text, published_at timestamptz, created_at timestamptz not null default now());
create table public.projects (id uuid primary key default uuid_generate_v4(), engineer_id uuid not null references public.profiles, title text not null, description text, url text, created_at timestamptz not null default now());
-- Enable RLS. Add role-specific policies before production; never expose service_role in the client.
alter table public.profiles enable row level security; alter table public.expert_profiles enable row level security; alter table public.assessment_tracks enable row level security; alter table public.availability_slots enable row level security; alter table public.assessments enable row level security; alter table public.scorecards enable row level security; alter table public.projects enable row level security;
create policy "public verified profiles" on public.profiles for select using (is_public = true or auth.uid() = id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "users read their assessments" on public.assessments for select using (auth.uid() = engineer_id or auth.uid() = expert_id);
create policy "users read relevant scorecards" on public.scorecards for select using (exists (select 1 from public.assessments a where a.id=assessment_id and (a.engineer_id=auth.uid() or a.expert_id=auth.uid())));

